version: 2.1

orbs:
  # define the orb for the circleci/cucumber
  cucumber: circleci/cucumber@1.1.6

jobs:
  build:
    # use the circleci/cucumber orb
    executor: cucumber/default
    # define the steps to run
    steps:
      - checkout
      # install java
      - run: sudo apt-get install -y openjdk-8-jdk
      # install maven
      - run: sudo apt-get install -y maven
      # run maven build and tests
      - run: mvn clean test -Dcucumber.options="--tags @smoke"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
